export const environment = {
  production: true,
  baseUrl: 'https://planetalab.xyz',
  // eslint-disable-next-line max-len
  token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjIxNTE4ODAsImV4cCI6MTY2MjM2Nzg4MCwiZGF0YSI6eyJpZCI6IjIiLCJyb2xlX2lkIjoiMiIsImNvbXBhbmllc19pZCI6IjEiLCJuYW1lIjoicHJ1ZWJhcyIsImVtYWlsIjoiaXBsYW5ldEBpcGxhbmV0Y29sb21iaWEuY29tIiwidXNlcm5hbWUiOiJwcnVlYmFzIiwicGFzc3dvcmQiOiIkMnkkMTAkUWh2WmJCN1wvdm9WRFlVWUVJSGM4VnVpVk9ua3hJV0x6NFVvQmhLYXVKN2RRSnJmOEFtZGsyIiwicGhvdG8iOiIxNjU1OTEzNjY3XzdjMzUwY2NhYmMyMjk5NDM5NzcxLnBuZyIsInN0YXR1cyI6ImFjdGl2ZSJ9fQ.JCynpvCkTpFuwHXJzjllDX1_7B5wMIn118NOSNTCICM'
};
